//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Status { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Manufacturer { get; set; }
        public string Article { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
